name: video_viewer_updated
description: Multiplatform minimalist video viewer with spectacular user experience.
homepage: https://github.com/seel-channel/video_viewer
version: 1.2.7
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  gesture_x_detector: ^1.0.0
  helpers:
    git:
      url: https://github.com/mitch2na/helpers.git
      ref: main
  http: ^0.13.0
  path_provider: ^2.0.6
  provider: ^6.0.5
  video_player: ^2.2.6
  volume_watcher: ^2.0.1
  wakelock: ^0.6.2
  video_player_web_hls: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
